backend:
  name: git-gateway
media_folder: public/img
collections:
  - name: "products" # Used in routes, e.g., /admin/collections/blog
    label: "Produtos" # Used in the UI
    folder: "_products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - {
          label: "Imagens",
          name: "imgs",
          widget: "list",
          field: { label: Image, name: image, widget: image },
        }
      - { label: "Descricao", name: "description", widget: "markdown" }
      - { label: "Quantidade", name: "qutd", widget: "number" }
      - { label: "Preco", name: "price", widget: "string" }
      - { label: "Categoria", name: "category", widget: "string" }
  - name: "location"
    label: "Localização"
    folder: "_location"
    create: false
    slug: "location"
    fields:
      - { label: "Endereço", name: "address", widget: "markdown" }
      - {
          label: "Contatos",
          name: "contacts",
          widget: "list",
          field: { label: "Contato", name: "contact", widget: "string" },
        }
