backend:
  name: git-gateway
media_folder: public/img
collections:
  - name: "products"
    label: "Produtos"
    folder: "_products"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - {
          label: "Imagens",
          name: "imgs",
          widget: "list",
          field: { label: Image, name: image, widget: image },
        }
      - { label: "Descricao", name: "description", widget: "markdown" }
      - { label: "Quantidade", name: "qutd", widget: "number" }
      - { label: "Preco", name: "price", widget: "string" }
      - { label: "Categoria", name: "category", widget: "string" }
  - name: "pages"
    label: "Páginas"
    files:
      - label: "Localização e Contato"
        name: "location"
        file: "_pages/location.yml"
        fields:
          - { label: "Endereço", name: "address", widget: "markdown" }
          - {
              label: "Contatos",
              name: "contacts",
              widget: "list",
              field: { label: "Contato", name: "contact", widget: "string" },
            }
