backend:
  name: git-gateway
media_library:
  name: cloudinary
  config:
    cloud_name: dqapaie8f
    api_key: 676736277633762
collections:
  - name: "products"
    label: "Produtos"
    extensions: "yml"
    folder: "_products"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - {
          label: "Imagens",
          name: "imgs",
          widget: "list",
          field: { label: Image, name: image, widget: image },
        }
      - { label: "Descricao", name: "description", widget: "markdown" }
      - { label: "Quantidade", name: "qutd", widget: "number" }
      - { label: "Preco", name: "price", widget: "string" }
      - {
          label: "Categoria",
          name: "category",
          widget: "custom-file-relation",
          collection: "pages",
          file: "categories",
          target_field: "categoriesList",
          id_field: "category",
          display_fields: "category",
        }
  - name: "pages"
    label: "Páginas"
    files:
      - label: "Localização e Contato"
        name: "location"
        file: "_pages/location.yml"
        fields:
          - { label: "Endereço", name: "address", widget: "markdown" }
          - {
              label: "Contatos",
              name: "contacts",
              widget: "list",
              field: { label: "Contato", name: "contact", widget: "string" },
            }
      - label: "Acessoria"
        name: "accessory"
        file: "_pages/accessory.yml"
        fields:
          - { label: "Texto", name: "text", widget: "markdown" }
          - {
              label: "Imagens",
              name: "imgs",
              widget: "list",
              field: { label: Image, name: image, widget: image },
            }
      - label: "Categorias"
        name: "categories"
        file: "_pages/categories.yml"
        fields:
          - {
              label: "Categorias",
              name: "categoriesList",
              widget: "list",
              field: { label: "Categoria", name: "category", widget: "string" },
            }
