backend:
  name: git-gateway
media_folder: "static/imgs"
public_folder: "/public/imgs"
collections:
  - name: "products" # Used in routes, e.g., /admin/collections/blog
    label: "Produtos" # Used in the UI
    folder: "_products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}-{{id}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "id", name: "id", widget: "hidden", default: "product" }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Imagens", name: "thumbnail", widget: "image" }
      - { label: "Descricao", name: "description", widget: "markdown" }
      - { label: "Quantidade", name: "qutd", widget: "number" }
      - { label: "Preco", name: "price", widget: "string" }
